package com.hpdxay.hpd3dmgame.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hpdxay.hpd3dmgame.entities.ChapterListItemDataItem;
import com.hpdxay.hpd3dmgame.entities.ChapterCommentListItemDataItem;

import com.hpdxay.hpd3dmgame.dao.ChapterListItemDataItemDao;
import com.hpdxay.hpd3dmgame.dao.ChapterCommentListItemDataItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chapterListItemDataItemDaoConfig;
    private final DaoConfig chapterCommentListItemDataItemDaoConfig;

    private final ChapterListItemDataItemDao chapterListItemDataItemDao;
    private final ChapterCommentListItemDataItemDao chapterCommentListItemDataItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chapterListItemDataItemDaoConfig = daoConfigMap.get(ChapterListItemDataItemDao.class).clone();
        chapterListItemDataItemDaoConfig.initIdentityScope(type);

        chapterCommentListItemDataItemDaoConfig = daoConfigMap.get(ChapterCommentListItemDataItemDao.class).clone();
        chapterCommentListItemDataItemDaoConfig.initIdentityScope(type);

        chapterListItemDataItemDao = new ChapterListItemDataItemDao(chapterListItemDataItemDaoConfig, this);
        chapterCommentListItemDataItemDao = new ChapterCommentListItemDataItemDao(chapterCommentListItemDataItemDaoConfig, this);

        registerDao(ChapterListItemDataItem.class, chapterListItemDataItemDao);
        registerDao(ChapterCommentListItemDataItem.class, chapterCommentListItemDataItemDao);
    }
    
    public void clear() {
        chapterListItemDataItemDaoConfig.getIdentityScope().clear();
        chapterCommentListItemDataItemDaoConfig.getIdentityScope().clear();
    }

    public ChapterListItemDataItemDao getChapterListItemDataItemDao() {
        return chapterListItemDataItemDao;
    }

    public ChapterCommentListItemDataItemDao getChapterCommentListItemDataItemDao() {
        return chapterCommentListItemDataItemDao;
    }

}
